# Generated by tools/generate_feature_contracts.py. DO NOT EDIT.

FEATURE_SET = 'market_features'

CURRENT_CONTRACT_VERSION = 'v4_10s'

REALIZED_VOL_WINDOWS = {'30s': 3, '1m': 6, '5m': 30, '15m': 90, '30m': 180, '1h': 360, '3h': 1080}

BUY_VOLUME_WINDOWS = {'30s': 3, '5m': 30, '10m': 60}

REALIZED_VOL_VERSIONS = ('v3_10s', 'v4_10s')

BUY_VOLUME_VERSIONS = ('v4_10s',)
