from __future__ import annotations

from typing import Any, Protocol

from .schemas import (
    FeatureObservation,
    MarketMetadata,
    Spot,
    Ticker,
    VolatilitySnapshot,
)


class MarketDataSource(Protocol):
    async def ensure_group(self) -> None: ...
    async def read_spot(self) -> Spot: ...
    async def read_features(self) -> FeatureObservation: ...
    async def bootstrap_tickers(self) -> list[Ticker]: ...
    async def consume_tickers(self) -> list[tuple[str, Ticker]]: ...
    async def acknowledge(self, entry_ids: list[str]) -> None: ...


class MetadataProvider(Protocol):
    async def markets(self, series_ticker: str, now_ms: int) -> dict[str, MarketMetadata]: ...


class ForecastProvider(Protocol):
    @property
    def ready(self) -> bool: ...
    async def forecast(self, observation: FeatureObservation, now_ms: int) -> VolatilitySnapshot: ...


class PricingPublisher(Protocol):
    async def publish_volatility(self, snapshot: VolatilitySnapshot) -> None: ...
    async def publish_price(self, market_ticker: str, payload: dict[str, Any]) -> None: ...
    async def unavailable(self, market_ticker: str, reason: str, now_ms: int) -> None: ...
    async def expire_inactive(self, active_tickers: set[str], now_ms: int) -> None: ...
    async def ping(self) -> bool: ...
