"""Generate service-local Python constants from the feature contract manifest."""

from __future__ import annotations

import argparse
import json
import pprint
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "feature_contracts" / "market_features.json"
HEADER = "# Generated by tools/generate_feature_contracts.py. DO NOT EDIT.\n\n"


def _literal(value: object) -> str:
    return pprint.pformat(value, width=100, sort_dicts=False)


def _module(**values: object) -> str:
    return HEADER + "\n\n".join(f"{name} = {_literal(value)}" for name, value in values.items()) + "\n"


def _load_manifest() -> dict:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    if manifest.get("schema_version") != 1:
        raise ValueError("unsupported feature contract manifest schema")
    feature_names = [feature["name"] for feature in manifest["features"]]
    if len(feature_names) != len(set(feature_names)):
        raise ValueError("feature names must be unique")
    known = set(feature_names)
    horizons = set(manifest["horizon_seconds"])
    for version, contract in manifest["contracts"].items():
        fields = contract["fields"]
        required = contract["required_fields"]
        if not set(fields) <= known or not set(required) <= set(fields):
            raise ValueError(f"{version} contains unknown or invalid fields")
        inputs = contract["model_inputs"]
        if set(inputs) != {"default"} and set(inputs) != horizons:
            raise ValueError(f"{version} must define default inputs or every horizon")
        if any(not set(columns) <= set(fields) for columns in inputs.values()):
            raise ValueError(f"{version} model inputs must belong to its fields")
    return manifest


def _render_targets(manifest: dict) -> dict[Path, str]:
    contracts = manifest["contracts"]
    ml_keys = (
        "feature_view", "feature_service", "offline_table", "label_version",
        "default_architecture", "fields", "model_inputs",
    )
    feast_keys = (
        "feature_view", "feature_service", "offline_table", "default_architecture", "fields",
        "required_fields",
    )
    ml_contracts = {
        version: {key: contract[key] for key in ml_keys}
        for version, contract in contracts.items()
    }
    feast_contracts = {
        version: {key: contract[key] for key in feast_keys}
        for version, contract in contracts.items()
    }
    field_types = {feature["name"]: feature["type"] for feature in manifest["features"]}
    kinds = {
        feature.get("calculation", {}).get("kind")
        for feature in manifest["features"]
    } - {None}
    calculations = {
        kind: {
            feature["calculation"]["window"]: feature["calculation"]["window_bars"]
            for feature in manifest["features"]
            if feature.get("calculation", {}).get("kind") == kind
        }
        for kind in kinds
    }
    return {
        ROOT / "services/batch_etl/scripts/generated_feature_contracts.py": _module(
            CURRENT_CONTRACT_VERSION=manifest["canonical_version"],
            CANONICAL_FEATURE_SQL=manifest["canonical_sql"],
        ),
        ROOT / "services/ml_pipeline/src/common/generated_feature_contracts.py": _module(
            FEATURE_SET=manifest["feature_set"],
            CURRENT_CONTRACT_VERSION=manifest["canonical_version"],
            HORIZON_SECONDS=manifest["horizon_seconds"],
            CONTRACT_DEFINITIONS=ml_contracts,
        ),
        ROOT / "services/feast_store/registry/generated_feature_contracts.py": _module(
            FEATURE_SET=manifest["feature_set"],
            CURRENT_CONTRACT_VERSION=manifest["canonical_version"],
            FIELD_TYPES=field_types,
            CONTRACT_DEFINITIONS=feast_contracts,
        ),
        ROOT / "services/live_feature_service/src/live_feature_service/generated_feature_contracts.py": _module(
            FEATURE_SET=manifest["feature_set"],
            CURRENT_CONTRACT_VERSION=manifest["canonical_version"],
            REALIZED_VOL_WINDOWS=calculations["realized_volatility"],
            BUY_VOLUME_WINDOWS=calculations["log_buy_volume"],
            REALIZED_VOL_VERSIONS=tuple(
                version for version, contract in contracts.items()
                if "realized_volatility" in contract["capabilities"]
            ),
            BUY_VOLUME_VERSIONS=tuple(
                version for version, contract in contracts.items()
                if "log_buy_volume" in contract["capabilities"]
            ),
        ),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, content in _render_targets(_load_manifest()).items():
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                stale.append(path.relative_to(ROOT))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    if stale:
        names = ", ".join(map(str, stale))
        raise SystemExit(f"generated feature contracts are stale: {names}")


if __name__ == "__main__":
    main()
